#Garbage
#  - windows
#    - os: windows
#compiler:
#    - clang
#matrix:
#  allow_failures:
#    - os: osx
#    - compilter: clang
os:
  - linux
  - osx
language: cpp
compiler:
  - gcc
  - clang
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
	brew update; fi
        brew install gsl; fi
	brew install gcc48; 
    fi

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
	sudo apt-get -qq update; 
	sudo apt-get install -y libgsl0-dev; 
	sudo apt-get install -y gettext; 
    fi
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
